### PR TITLE
Newsletter/27

### PR DESCRIPTION
**Pull request by thomasdebeus**

### CODE REVIEW

**Comment by bvhme** [comment]
Cool, I'll pull this into the Mailchimp after checking it out!

@thomasdebeus, @SPrinss, @lkattie I propose we make new PR's to this one when we want to change something not trivial (like a typo)

**Comment by bvhme** [comment]
OK, I think it is good to go!

**Comment by thomasdebeus** [comment]
Nice, what about the background of the header?

**Comment by thomasdebeus** [comment]
Maybe this weeks gif is also well suited for the job!

**Comment by bvhme** [comment]
Yeah, cool

**Comment by bvhme** [comment]
I'll put it in

**Comment by bvhme** [comment]
Version without the gif
https://circle-artifacts.com/gh/newatoms/hwhbstptw/33/artifacts/0/home/ubuntu/hwhbstptw/_site/newsletters/18-12-15-27.html

**Comment by SPrinss** [comment]
Great  :+1:

**Comment by bvhme** [comment]
Maybe we can simplify the subject still, making it more clickable?

**Comment by SPrinss** [comment]
oh it's not 'gone where'  I think

**Comment by thomasdebeus** [comment]
I can't see the image that belongs to: Gone were the days....

And there are a lot of crazy squares after some emojis... I think only the skinned 👏🏻emojis

**Comment by thomasdebeus** [comment]
Can you also send a test email to me if you're ready?

**Pull request merged**
