### PR TITLE
A new idea for a call to action to be big on the site

### PR DESCRIPTION
**Pull request by bvhme**
with @newatoms/lots-of-people

### CODE REVIEW

**Comment by bvhme** [comment]
What do you think @thomasdebeus?

**Comment by thomasdebeus** [comment]
Yes, bold but yeah cool.

**Comment by thomasdebeus** [comment]
Maybe _things_ are too generic? What about fucking awesome future?

**Comment by bvhme** [comment]
@thomasdebeus, I think future might be too vague

**Comment by bvhme** [comment]
Okay, this discussion is not over, but I want to merge this one already and keep discussing, is that okay with you @thomasdebeus

**Comment by thomasdebeus** [comment]
Yes, of course

On 18 December 2015 at 16:02, Boris van Hoytema notifications@github.com
wrote:

> Okay, this discussion is not over, but I want to merge this one already
> and keep discussing, is that okay with you @thomasdebeus
> https://github.com/thomasdebeus
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/newatoms/hwhbstptw/pull/10#issuecomment-165798824.

## 

Thomas de Beus
Tel. nr.: 0683793937
Email:   thomasdebeus@gmail.com

**Pull request merged**
